### ISSUE TITLE
GAEにrailsアプリをデプロイする

### ISSUE THREAD

**Issue by aokabin** [aokabin/rails-on-gae#1]
# アプリケーションデプロイ

## Railsアプリケーションを初期化

```bash
$ rails new .
$ bundle install --path vendor/bundle --without production
$ rails g scaffold blog title:string content:text
$ rails db:migrate
$ rails s
```

サーバーが立ち上がったのを確認

**Comment by aokabin** [comment]
## 完全にチュートリアルがあった

[Google App Engine フレキシブル環境での Rails 5 の実行  \|  Ruby  \|  Google Cloud](https://cloud.google.com/ruby/rails/appengine)

これ通りに進めてみる

**Comment by aokabin** [comment]
アプリケーションはあるので、`app.yaml`を作成するところから進めてみる

```yaml
entrypoint: bundle exec rackup --port $PORT
env: flex
runtime: ruby
```

次にrailsのsecretを作成

```bash
$ bundle exec rails secret | pbcopy
```

app.yamlに貼り付ける

```yaml

entrypoint: bundle exec rackup -p $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: [ここに貼る]
```
